In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
le = LabelEncoder()

In [4]:
data = pd.read_csv('data.csv')

In [5]:
for column in data.columns:
    data[column] = le.fit_transform(data[column])

In [6]:
labels = data['Incident Type']
data.drop('Incident Type', axis=1, inplace=True)

In [7]:
train, cv, target, target_cv = train_test_split(data, labels, test_size=0.08)

In [8]:
train.shape, cv.shape, target.shape, target_cv.shape

((920, 9), (80, 9), (920,), (80,))

In [10]:
train

,Primary Cause,Cause Class,Cause Type,Working Condition,Machine Condition,SOP Requirement,SOP Availability,SOP Adequacy,SOP Compliance
71,11,0,0,0,0,1,0,0,0
681,0,1,1,2,0,2,2,2,2
556,2,1,1,2,2,0,0,2,1
443,11,0,2,1,1,1,1,0,0
113,10,1,2,2,0,0,1,2,1
839,8,0,1,2,0,0,1,1,1
304,1,0,1,0,1,1,2,2,2
832,5,1,0,2,0,2,1,1,1
55,10,1,3,2,2,1,1,2,0
785,10,1,3,2,1,1,1,0,1
430,0,1,2,1,1,1,0,2,2
186,9,1,1,1,2,0,2,2,1
39,4,1,0,2,2,1,1,2,0
774,7,0,0,0,0,0,0,1,0
179,8,0,2,0,2,1,2,0,2
74,9,1,1,2,0,1,2,2,2
939,10,0,0,1,2,1,1,1,0
641,8,1,0,1,2,1,1,1,1
152,4,1,2,1,1,1,1,2,0
621,4,0,3,1,1,0,0,0,1
976,9,1,2,0,1,0,1,1,0
268,2,1,2,1,2,0,0,2,0
793,11,1,3,2,1,2,0,0,1
318,6,0,2,0,2,1,2,0,1
373,9,1,0,0,2,0,0,2,2
352,1,0,3,1,2,1,1,2,0
930,5,1,2,2,0,1,2,1,2
145,0,0,1,1,0,2,1,0,0
703,0,1,2,0,2,0,1,1,1
921,0,1,3,2,1,1,2,0,1
...,...,...,...,...,...,...,...,...,...
932,2,1,0,2,0,0,1,0,0
638,8,0,2,2,2,0,1,0,0
741,11,0,3,0,1,2,1,2,0
935,8,0,0,2,0,0,1,2,1
603,7,0,0,0,1,2,0,0,1
961,7,1,0,1,1,0,1,2,1
940,10,0,3,1,0,0,2,0,0
206,0,1,0,2,2,2,1,0,1
865,2,0,1,1,2,0,1,1,2
94,11,0,2,1,2,1,0,2,1
599,0,0,2,0,1,2,1,0,0
218,9,0,2,1,1,0,0,1,0
494,11,1,2,0,1,1,2,2,0
535,2,1,2,0,2,2,0,0,1
19,4,0,3,1,2,2,1,2,0
955,11,1,1,2,1,1,2,0,0
285,9,1,0,2,0,0,0,0,0
171,1,1,2,2,2,1,0,2,1
160,9,0,1,1,0,0,1,2,1
280,0,1,3,0,0,1,0,1,0
933,6,0,0,0,1,0,0,0,1
562,4,0,3,0,1,2,2,0,2
464,0,0,0,1,0,0,1,2,2
32,6,1,2,2,2,2,0,0,2
582,7,1,0,2,2,0,1,2,2
672,5,1,3,2,2,2,0,1,1
468,4,0,2,2,2,1,2,0,2
244,9,0,3,1,2,1,0,2,0
91,1,0,2,1,2,1,2,1,0
60,9,1,0,0,2,2,2,0,1

In [11]:
target

71     1
681    2
556    1
443    0
113    2
839    1
304    0
832    2
55     2
785    0
430    1
186    1
39     0
774    0
179    2
74     0
939    0
641    1
152    0
621    2
976    2
268    0
793    1
318    1
373    1
352    1
930    1
145    1
703    1
921    0
      ..
932    2
638    0
741    2
935    0
603    0
961    0
940    0
206    1
865    2
94     0
599    0
218    1
494    0
535    0
19     1
955    2
285    0
171    1
160    2
280    0
933    0
562    0
464    2
32     1
582    1
672    0
468    2
244    2
91     0
60     1
Name: Incident Type, Length: 920, dtype: int64